# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'Ahmet Enis Cetin-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Author',  url: 'Author'}
- {name: 'Publications',      url: 'documentation'}
- {name: 'Contact',            url: 'contact'}
- {name: 'Students',            url: 'students'}


